ecommerce_dwh:
  target: dev

  outputs:
    dev:
      type: postgres
      host: localhost
      port: "{{ env_var('POSTGRES_DWH_HOST_PORT') | int }}"
      user: "{{ env_var('POSTGRES_DWH_USER') }}"
      password: "{{ env_var('POSTGRES_DWH_PASS') }}"
      dbname: "{{ env_var('POSTGRES_DWH_DB') }}"
      schema: public
      threads: 4